import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConnectContext } from "./context/index";
import Home from "./page";
import { AppContext } from "./context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <ConnectContext>
          <AppContext>
            <Home />
          </AppContext>
        </ConnectContext>
      </body>

    </html>
  );
}
